version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${_saPassword}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    expose: 
      - "1433"
    networks:
      - ecinema-2025
    # volumes:
    #   - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${_rabbitMqUser}
      - RABBITMQ_DEFAULT_PASS=${_rabbitMqPassword}
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 5672
      - 15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - ecinema-2025

  ecinema-api:
    build:
      context: .
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5190
      - ConnectionStrings__DefaultConnection=Server=${_source},1433;Database=${_catalog};User=sa;Password=${_saPassword};ConnectRetryCount=0;TrustServerCertificate=True
      - _saPassword=${_saPassword}
      - _rabbitMqHost=${_rabbitMqHost}
      - _rabbitMqUser=${_rabbitMqUser}
      - _rabbitMqPassword=${_rabbitMqPassword}
      - _rabbitMqPort=${_rabbitMqPort}
      - _fromAddress=${_fromAddress}
      - _password=${_password}
      - _host=${_host}
      - _enableSSL=${_enableSSL}
      - _displayName=${_displayName}
      - _timeout=${_timeout}
      - _port=${_port}
    ports:
      - "5190:5190"
    networks:
      - ecinema-2025
    links:
      - sqlserver
    depends_on:
      - sqlserver
      - rabbitmq

  subscriber:
    build:
      context: .
      dockerfile: eCinema.Subscriber/Dockerfile
    restart: on-failure
    environment:
      - _fromAddress=${_fromAddress}
      - _password=${_password}
      - _host=${_host}
      - _enableSSL=${_enableSSL}
      - _displayName=${_displayName}
      - _timeout=${_timeout}
      - _port=${_port}
      - _rabbitMqHost=${_rabbitMqHost}
      - _rabbitMqUser=${_rabbitMqUser}
      - _rabbitMqPassword=${_rabbitMqPassword}
      - _rabbitMqPort=${_rabbitMqPort}
    networks:
      - ecinema-2025
    depends_on:
      - rabbitmq

# volumes:
#   sqlserver_data:
networks:
  ecinema-2025:
    driver: bridge
